services:
  server:
    image: alexlead17/mooc_docker_3_2:latest
    build:
      context: ./src
    ports:
      - "8080:8080"
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Check for updates every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower